services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.prod

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME={DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD={DB_PASSWORD}
      - MONGO_INITDB_DATABASE={DB_NAME}

volumes:
  mongo_data:
      